namespace DataInsights.Models
{
    public class ProcessedStackoverflowModel
    {
        public int Id { get; set; }
        public YearBand YearsCoding { get; set; }
        public YearBand YearsProfessionalCoding { get; set; }
        public decimal Salary { get; set; }
        public bool HasAdditionalEducation { get; set; }
        public bool Kenya { get; set; }
        public bool UnitedKingdom { get; set; }
        public bool UnitedStates { get; set; }
        public bool SouthAfrica { get; set; }
        public bool Nigeria { get; set; }
        public bool India { get; set; }
        public bool Spain { get; set; }
        public bool Croatia { get; set; }
        public bool Netherlands { get; set; }
        public bool Israel { get; set; }
        public bool Sweden { get; set; }
        public bool Chile { get; set; }
        public bool Australia { get; set; }
        public bool Greece { get; set; }
        public bool Poland { get; set; }
        public bool Belgium { get; set; }
        public bool Argentina { get; set; }
        public bool Germany { get; set; }
        public bool RussianFederation { get; set; }
        public bool Indonesia { get; set; }
        public bool Ireland { get; set; }
        public bool France { get; set; }
        public bool Ukraine { get; set; }
        public bool Denmark { get; set; }
        public bool DominicanRepublic { get; set; }
        public bool China { get; set; }
        public bool Latvia { get; set; }
        public bool Algeria { get; set; }
        public bool Colombia { get; set; }
        public bool Japan { get; set; }
        public bool Finland { get; set; }
        public bool Romania { get; set; }
        public bool Brazil { get; set; }
        public bool Bulgaria { get; set; }
        public bool IslamicRepublicOfIran { get; set; }
        public bool Nepal { get; set; }
        public bool Bangladesh { get; set; }
        public bool Pakistan { get; set; }
        public bool Canada { get; set; }
        public bool Jordan { get; set; }
        public bool Portugal { get; set; }
        public bool Italy { get; set; }
        public bool NewZealand { get; set; }
        public bool Turkey { get; set; }
        public bool CzechRepublic { get; set; }
        public bool VietNam { get; set; }
        public bool Austria { get; set; }
        public bool Egypt { get; set; }
        public bool Malaysia { get; set; }
        public bool Mozambique { get; set; }
        public bool Thailand { get; set; }
        public bool Slovakia { get; set; }
        public bool Lebanon { get; set; }
        public bool Mexico { get; set; }
        public bool HongKongSar { get; set; }
        public bool Norway { get; set; }
        public bool Myanmar { get; set; }
        public bool Switzerland { get; set; }
        public bool SouthKorea { get; set; }
        public bool Hungary { get; set; }
        public bool Armenia { get; set; }
        public bool Kazakhstan { get; set; }
        public bool UnitedArabEmirates { get; set; }
        public bool Singapore { get; set; }
        public bool Qatar { get; set; }
        public bool BosniaAndHerzegovina { get; set; }
        public bool Bahrain { get; set; }
        public bool SriLanka { get; set; }
        public bool Cambodia { get; set; }
        public bool Serbia { get; set; }
        public bool Philippines { get; set; }
        public bool Peru { get; set; }
        public bool Botswana { get; set; }
        public bool Paraguay { get; set; }
        public bool Georgia { get; set; }
        public bool Uruguay { get; set; }
        public bool Belarus { get; set; }
        public bool Lithuania { get; set; }
        public bool Afghanistan { get; set; }
        public bool Estonia { get; set; }
        public bool Malta { get; set; }
        public bool CostaRica { get; set; }
        public bool Ghana { get; set; }
        public bool Taiwan { get; set; }
        public bool Morocco { get; set; }
        public bool Albania { get; set; }
        public bool SaudiArabia { get; set; }
        public bool Slovenia { get; set; }
        public bool Uzbekistan { get; set; }
        public bool RepublicOfKorea { get; set; }
        public bool ElSalvador { get; set; }
        public bool Iceland { get; set; }
        public bool BolivarianRepublicOfVenezuela { get; set; }
        public bool Nicaragua { get; set; }
        public bool OtherCountry { get; set; }
        public bool Tunisia { get; set; }
        public bool TheFormerYugoslavRepublicOfMacedonia { get; set; }
        public bool FederatedStatesOfMicronesia { get; set; }
        public bool Madagascar { get; set; }
        public bool Rwanda { get; set; }
        public bool Yemen { get; set; }
        public bool Uganda { get; set; }
        public bool UnitedRepublicOfTanzania { get; set; }
        public bool Cameroon { get; set; }
        public bool Cuba { get; set; }
        public bool Ethiopia { get; set; }
        public bool Oman { get; set; }
        public bool Ecuador { get; set; }
        public bool Angola { get; set; }
        public bool RepublicOfMoldova { get; set; }
        public bool Honduras { get; set; }
        public bool Azerbaijan { get; set; }
        public bool Cyprus { get; set; }
        public bool Bhutan { get; set; }
        public bool Guatemala { get; set; }
        public bool SyrianArabRepublic { get; set; }
        public bool Kuwait { get; set; }
        public bool Luxembourg { get; set; }
        public bool Jamaica { get; set; }
        public bool Zimbabwe { get; set; }
        public bool SanMarino { get; set; }
        public bool Fiji { get; set; }
        public bool Liechtenstein { get; set; }
        public bool Burundi { get; set; }
        public bool Bolivia { get; set; }
        public bool Mauritius { get; set; }
        public bool Somalia { get; set; }
        public bool Montenegro { get; set; }
        public bool Mongolia { get; set; }
        public bool Sudan { get; set; }
        public bool Maldives { get; set; }
        public bool Turkmenistan { get; set; }
        public bool Panama { get; set; }
        public bool Barbados { get; set; }
        public bool Lesotho { get; set; }
        public bool Namibia { get; set; }
        public bool Gabon { get; set; }
        public bool Kyrgyzstan { get; set; }
        public bool Swaziland { get; set; }
        public bool AntiguaAndBarbuda { get; set; }
        public bool MarshallIslands { get; set; }
        public bool TrinidadAndTobago { get; set; }
        public bool Senegal { get; set; }
        public bool Iraq { get; set; }
        public bool Haiti { get; set; }
        public bool Malawi { get; set; }
        public bool Benin { get; set; }
        public bool LibyanArabJamahiriya { get; set; }
        public bool Tajikistan { get; set; }
        public bool DemocraticRepublicOfTheCongo { get; set; }
        public bool Andorra { get; set; }
        public bool Guinea { get; set; }
        public bool CoteDIvoire { get; set; }
        public bool Bahamas { get; set; }
        public bool CentralAfricanRepublic { get; set; }
        public bool Monaco { get; set; }
        public bool Gambia { get; set; }
        public bool SierraLeone { get; set; }
        public bool Togo { get; set; }
        public bool Palau { get; set; }
        public bool Zambia { get; set; }
        public bool Grenada { get; set; }
        public bool BurkinaFaso { get; set; }
        public bool Belize { get; set; }
        public bool RepublicOfTheCongo { get; set; }
        public bool Suriname { get; set; }
        public bool TimorLeste { get; set; }
        public bool Dominica { get; set; }
        public bool SolomonIslands { get; set; }
        public bool SaintLucia { get; set; }
        public bool Niger { get; set; }
        public bool Guyana { get; set; }
        public bool Nauru { get; set; }
        public bool Mauritania { get; set; }
        public bool Mali { get; set; }
        public bool Liberia { get; set; }
        public bool BruneiDarussalam { get; set; }
        public bool NorthKorea { get; set; }
        public bool CapeVerde { get; set; }
        public bool Eritrea { get; set; }
        public bool DemocraticPeoplesRepublicOfKorea { get; set; }
        public bool Djibouti { get; set; }
        public bool GuineaBissau { get; set; }
        public bool No { get; set; }
        public bool PartTimeStudent { get; set; }
        public bool FullTimeStudent { get; set; }
        public bool FullTime { get; set; }
        public bool PartTime { get; set; }
        public bool Retired { get; set; }
        public bool Independent { get; set; }
        public bool NoEducation { get; set; }
        public bool Primary { get; set; }
        public bool Secondary { get; set; }
        public bool Foundation { get; set; }
        public bool Associate { get; set; }
        public bool Professional { get; set; }
        public bool Bachelors { get; set; }
        public bool Masters { get; set; }
        public bool Doctoral { get; set; }
        public bool Business { get; set; }
        public bool HealthScience { get; set; }
        public bool Humanities { get; set; }
        public bool NaturalScience { get; set; }
        public bool SocialScience { get; set; }
        public bool Engineering { get; set; }
        public bool ComputerScience { get; set; }
        public bool Arts { get; set; }
        public bool Undeclared { get; set; }
        public bool Information { get; set; }
        public bool Maths { get; set; }
        public bool None { get; set; }
        public bool Web { get; set; }
        public bool FullStackDeveloper { get; set; }
        public bool DatabaseAdministrator { get; set; }
        public bool DevOpsSpecialist { get; set; }
        public bool SystemAdministrator { get; set; }
        public bool EngineeringManager { get; set; }
        public bool DataOrBusinessAnalyst { get; set; }
        public bool DesktopOrEnterpriseApplicationsDeveloper { get; set; }
        public bool GameOrGraphicsDeveloper { get; set; }
        public bool QaOrTestDeveloper { get; set; }
        public bool Student { get; set; }
        public bool BackEndDeveloper { get; set; }
        public bool FrontEndDeveloper { get; set; }
        public bool Designer { get; set; }
        public bool CSuiteExecutive { get; set; }
        public bool MobileDeveloper { get; set; }
        public bool DataScientistOrMachineLearningSpecialist { get; set; }
        public bool MarketingOrSalesProfessional { get; set; }
        public bool ProductManager { get; set; }
        public bool EmbeddedApplicationsOrDevicesDeveloper { get; set; }
        public bool EducatorOrAcademicResearcher { get; set; }
    }
}
